---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: metricsmultiplexer
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: metricsmultiplexer-metricsreader
rules:
- apiGroups:
  - external.metrics.k8s.io
  resources: ["*"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: metricsmultiplexer
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: metricsmultiplexer-metricsreader
subjects:
- kind: ServiceAccount
  name: metricsmultiplexer
  namespace: {{ .Release.Namespace }}
